#!/usr/bin/env python3

import random
import time

start_generate = time.time()
liste_random = [random.randint(1, 1000000) for number in range(1000000)]
end_generate = time.time() - start_generate

start_trie = time.time()
liste_trie = sorted(liste_random)
end_trie = time.time() - start_trie

print("Générer des nombres aléatoires a prit : " + str(end_generate) + " secondes")
print("Trier les nombres aléatoires a prit : " + str(end_trie) + " secondes")
print("Le plus petit nombre généré est : " + str(liste_trie[0]))
print("Le plus grand nombre généré est : " + str(liste_trie[-1]))
