#!/usr/bin/env python3

import pygame
import time

pygame.init()

fenetre = pygame.display.set_mode((600, 600))
image_fond = pygame.image.load("day08/hangman/assets/carreaux_de_cahier.png")

def charger_fond(image_fond):
    largeur_image = image_fond.get_width()
    hauteur_image = image_fond.get_height()
    # on souhaite centrer l'image --> marge = (taille fenêtre - taille image), divisée par 2 pour répartir également de chaque côté
    x=(600 - largeur_image) // 2 
    y=(600 - hauteur_image) // 2
    fenetre.blit(image_fond, (x, y))

def afficher_fond(image_fond):
    charger_fond(image_fond)
    pygame.display.flip()

def dessiner_homme_baton(fenetre):
    # Je commence par la tête à la position (300, 200) : le centre du cercle, avec un rayon de 50 et une épaisseur de 5
    pygame.draw.circle(fenetre, (128, 0, 32), (300, 200), 50, 5)
    # Je continue avec le corps, à hauteur 250 pour prendre en compte la tête, et une longueur de 150
    pygame.draw.line(fenetre, (128, 0, 32), (300, 250), (300, 400), 5)
    # Je dessine les bras, à hauteur 250, et une longueur de 50
    pygame.draw.line(fenetre, (128, 0, 32), (300, 250), (250, 300), 5)
    pygame.draw.line(fenetre, (128, 0, 32), (300, 250), (350, 300), 5)
    # Je termine avec les jambes, à hauteur 400, et une longueur de 50
    pygame.draw.line(fenetre, (128, 0, 32), (300, 400), (250, 450), 5)
    pygame.draw.line(fenetre, (128, 0, 32), (300, 400), (350, 450), 5)
    pygame.display.flip()

def etabli_de_pendaison(fenetre):
    gris_clair = (200, 200, 200)
    # base horizontale au sol
    pygame.draw.line(fenetre, gris_clair, (150, 500), (350, 500), 5)
    # poteau vertical
    pygame.draw.line(fenetre, gris_clair, (200, 500), (200, 100), 5)
    # traverse horizontale en haut
    pygame.draw.line(fenetre, gris_clair, (200, 100), (300, 100), 5)
    # support diagonal, pour la stabilité visuelle de la traverse
    pygame.draw.line(fenetre, gris_clair, (200, 130), (240, 100), 5)
    # corde, reliant la traverse à la tête du bonhomme
    pygame.draw.line(fenetre, gris_clair, (300, 100), (300, 150), 5)
    pygame.display.flip()

afficher_fond(image_fond)
etabli_de_pendaison(fenetre)
dessiner_homme_baton(fenetre)

continuer = True

while continuer:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            continuer = False

pygame.quit()