#!/usr/bin/env python3
import time

def ma_puissance(base, exposant):
    resultat = 1
    for _ in range(exposant):
        resultat = resultat * base
    return resultat

start_puissanc84 = time.time()
resultat_puissance84 = ma_puissance(42, 84)
end_puissance84 = time.time() - start_puissanc84

start_puissance168 = time.time()
resultat_puissance168 = ma_puissance(42, 168)
end_puissance168 = time.time() - start_puissance168

print("Calculer 42 à la puissance 84 a prit : " + str(round(end_puissance84, 6)) + " secondes")
print("Calculer 42 à la puissance 168 a prit : " + str(round(end_puissance168, 6)) + " secondes")