#!/usr/bin/env python3

import random
import unicodedata
import sys
import time

if len(sys.argv) > 1:
    max_penalites = int(sys.argv[1])
else:
    max_penalites = 12

def choix_aleatoire(collection):
    return random.choice(list(collection))

from english_words import get_english_words_set
mots_anglais = get_english_words_set(['web2'], lower=True)

def nettoyage(mot_a_deviner):
    mot = ""
    for letter in mot_a_deviner:
        letter_decompose = unicodedata.normalize("NFD", letter)
        for caractere in letter_decompose:
            if caractere.isalpha():
                mot += caractere.lower()
    return mot

def afficher_mot(mot, lettres_devinees):
    guess = ""
    for letter in mot:
        if letter in lettres_devinees:
            guess += letter.upper()
        else:
            guess += " _ "
    return guess

penalite = 0

lettres_tentees = set()

def points(tentative):
    global penalite
    if len(tentative) == 1:
        if tentative in lettres_tentees:
            print("YOU HAVE ALREADY TRIED THIS LETTER, TRY AGAIN.")
            return False
        lettres_tentees.add(tentative)
        if tentative in mot:
            lettres_devinees.add(tentative)
        else:
            penalite += 1
        return False
    else:
        if tentative == mot:
            return True
        else:
            penalite += 5
        return False

mot_a_deviner = choix_aleatoire(mots_anglais)
mot = nettoyage(mot_a_deviner)
lettres_devinees = set()

print()
print("________________________________________________________")
print()
print()
print("WELCOME TO HANGMAN, GUESS THE SECRET WORD TO SURVIVE!")
print()
print("WARNING!")
print("ONLY " + str(max_penalites) + " MISTAKES ARE ALLOWED.")
print("A WRONG LETTER WILL COST YOU 1 PENALTY, BUT A WRONG FULL WORD WILL COST YOU 5!")
print("THE WORD HAS " + str(len(mot)) + " LETTER(S).")
print("YOU HAVE A MAXIMUM OF 2 MINUTES TO FIND THE WORD!")
print()
print("MAY THE ODDS BE EVER IN YOUR FAVOR.")
print()

temps_depart = time.time()

while True:
    print(afficher_mot(mot, lettres_devinees))
    print()
    print("YOUR PENALTIES: " + str(penalite) + "/" + str(max_penalites) + " ; YOU HAVE " + str(max_penalites - penalite) + " CHANCES LEFT!")
    print()
    print()
    print("________________________________________________________")
    tentative = input("PLAYER, PROPOSE A LETTER OR A FULL WORD: ")
    tentative_nettoyee = nettoyage(tentative)
    victoire = points(tentative_nettoyee)
    if victoire:
        print()
        print()
        print("CONGRATULATIONS, YOU WIN! YOU SURVIVE.")
        print("THE WORD TO GUESS WAS: " + mot_a_deviner.upper())
        break
    if penalite >= max_penalites:
        print()
        print()
        print("FATE WAS NOT ON YOUR SIDE, YOU'RE GOING TO BE HANGED. DEFEAT")
        print("THE WORD TO GUESS WAS: " + mot_a_deviner.upper())
        break
    if set(mot) == lettres_devinees:
        print()
        print()
        print("CONGRATULATIONS, YOU WIN! YOU SURVIVE.")
        print("THE WORD TO GUESS WAS: " + mot_a_deviner.upper())
        break
    if time.time() - temps_depart > 120:
        print()
        print()
        print("YOU TOOK TOO LONG! YOU'RE GOING TO BE HANGED. DEFEAT")
        print("THE WORD TO GUESS WAS: " + mot_a_deviner.upper())
        break