#!/usr/bin/env python3

import unicodedata
import getpass
import sys
import time

if len(sys.argv) > 1:
    max_penalites = int(sys.argv[1])
else:
    max_penalites = 12

mot_a_deviner = getpass.getpass("MAÎTRE DU JEU, DONNEZ VOTRE MOT À DEVINER : ")

def nettoyage(mot_a_deviner):
    mot = ""
    for letter in mot_a_deviner:
        letter_decompose = unicodedata.normalize("NFD", letter)
        for caractere in letter_decompose:
            if caractere.isalpha():
                mot += caractere.lower()
    return mot

def afficher_mot(mot, lettres_devinees):
    guess = ""
    for letter in mot:
        if letter in lettres_devinees:
            guess += letter.upper() + " "
        else:
            guess += "_ "
    return guess

penalite = 0

lettres_tentees = set()

def points(tentative):
    global penalite
    if len(tentative) == 1:
        if tentative in lettres_tentees:
            print("VOUS AVEZ DÉJÀ TENTÉ CETTE LETTRE, VEUILLEZ EN PROPOSER UNE AUTRE.")
            return False
        lettres_tentees.add(tentative)
        if tentative in mot:
            lettres_devinees.add(tentative)
        else:
            penalite += 1
        return False
    else:
        if tentative == mot:
            return True
        else:
            penalite += 5
        return False

mot = nettoyage(mot_a_deviner)
lettres_devinees = set()

print("\n________________________________________________________ \n \n \nBIENVENUE AU JEU DU PENDU, TROUVEZ LE MOT SECRET POUR SURVIVRE !\n \nATTENTION !\nSEULES " + str(max_penalites) + " ERREURS VOUS SERONT PERMISES. \nUNE MAUVAISE LETTRE VOUS COÛTERA 1 PENALITE, MAIS UN MOT COMPLET ERRONÉ VOUS EN COÛTERA 5 ! \nLE MOT A DEVINER A " + str(len(mot)) + " LETTRE(S). \nVOUS DISPOSEZ DE 2 MINUTES MAXIMUM POUR TROUVER LE MOT \nPUISSE LE SORT VOUS ÊTRE FAVORABLE. \n")

temps_depart = time.time()

while True:
    print("\n" + afficher_mot(mot, lettres_devinees) + "\n VOS PÉNALITÉS SONT AU NOMBRE DE : " + str(penalite) + "/" + str(max_penalites) + " ; ATTENTION, IL VOUS RESTE " + str(max_penalites - penalite) + " CHANCES !" "\n \n________________________________________________________ \nATTENTION, IL VOUS RESTE " + str(120 - int(time.time() - temps_depart)) + " SECONDES !")
    tentative = input("JOUEUR, TENTEZ VOTRE CHANCE ET PROPOSEZ UNE LETTRE, OU UN MOT COMPLET : ")
    tentative_nettoyee = nettoyage(tentative)
    victoire = points(tentative_nettoyee)
    if victoire:
        print("\n \nVOUS REMPORTEZ LA PARTIE ! VOUS OBTENEZ LE DROIT DE SURVIVRE. \nLE MOT À DEVINER ÉTAIT : " + mot_a_deviner.upper())
        break
    if penalite >= max_penalites:
        print("\n \nLE SORT VOUS A ÉTÉ DÉFAVORABLE, VOUS ALLEZ ÊTRE PENDU, DEFAITE. \nLE MOT À DEVINER ÉTAIT : " + mot_a_deviner.upper())
        break
    if set(mot) == lettres_devinees:
        print("\n \nVOUS REMPORTEZ LA PARTIE ! VOUS OBTENEZ LE DROIT DE SURVIVRE. \nLE MOT À DEVINER ÉTAIT : " + mot_a_deviner.upper())
        break
    if time.time() - temps_depart > 120:
        print("\n \nVOUS AVEZ PRIS TROP DE TEMPS ! DERNIERE TENTATIVE AVANT LA DEFAITE !")
        tentative = input("JOUEUR, TENTEZ VOTRE CHANCE ET PROPOSEZ UN MOT COMPLET : ")
        tentative_nettoyee = nettoyage(tentative)
        if tentative_nettoyee == mot:
            print("\n \nVOUS REMPORTEZ LA PARTIE ! VOUS OBTENEZ LE DROIT DE SURVIVRE. \nLE MOT À DEVINER ÉTAIT : " + mot_a_deviner.upper())
            break
        else:
            print("\n \nLE SORT VOUS A ÉTÉ DÉFAVORABLE, VOUS ALLEZ ÊTRE PENDU, DEFAITE. \nLE MOT À DEVINER ÉTAIT : " + mot_a_deviner.upper())
            break